sudo: required

language: ruby

services:
  - docker

before_script:
  - docker rmi -f philasfwork/sfmc-swagger-ui
  - docker rmi -f registry.heroku.com/sfmc-travis-tests/web

script:
  - docker build ./main -t philasfwork/sfmc-swagger-ui
  - docker images

deploy: 
  # is this all I need?
  provider: heroku
  # run "travis encrypt $(heroku auth:token) --add deploy.api_key"
  # otherwise you will have to find and encrypt the Heroku key and put it in the tag below.
  api_key:
    secure: RhvjouAdhPhHKAOfhY0RmOgj1UdxKzwvZqaDpmNCKrY8Pd6I88SqpVfwM4NKBA9KfrPCfPrj1B+KES/s+kk8cKypWNxQIcWftlvfZsVLbP3bG1VysV5eCDsUhnafUfIFavu5y1YEWMnLihCbnn7GY5o0dhrGh52aSiNv/uTa8Je3o/Udgf6Y/EEl3+/56AAmttRg82HpFxnkKQ5GHFXcBNXIil9Fk+i1uIQfFxAZb/DOdRQ07f2bg/ZmThti8AsNPC37Fh2IoQse37CvcLwbIfUJZlpnG2NhE06ULwxLX6hxl+c2bNZURiBEoLWpjfrpsxE1/e3cXF/rPZt9Urzdf8mMf04P6t0J3j1Ik/2pFLE2OXCTPcErwkVNo7gujQ+o5HjQnXD582d/sHKVmOxQheV8vo3tlC442ptzf6cqdwL5wI+JUcom//XdI/C1vRH86asz1Q30wVJ81+s7dvCFlowD2BA3sCWMHGAMM5CjljlUPRH/CQz2r1AZwa7O8xgeh7ohyJvtPjMxX4kjXQn6pXzr0arjMkkd62CSjqrILCl6EK4/SQ7PPdZRhxs9Fl3YzhOfROm3qRrDJz+0ddSXyKWn0CANP13a2Y6LD44LSbTRq567Y3c0AB3/aW2rYVQb4WQoExbI/53c2Tzhp7Jie+HAqfq0SxdaczR+I1bWzjk=
  app: sfmc-travis-tests