sudo: required
language: ruby
services:
  - docker
before_script:
  - docker rmi -f philasfwork/sfmc-swagger-ui
  - docker rmi -f registry.heroku.com/sfmc-travis-tests/web
script:
  - docker build ./main -t philasfwork/sfmc-swagger-ui
  - docker images
deploy:
  provider: heroku
  api_key:
    secure: arBdFF8DRB0DFP3yO2kJCtinAS/0ZC7OOw8RkufU8+pm0zFJSwUfcojE0Bcy6KIGH4UYdsEZa9FHatSFExirLCMTYwsg3vey/I8tP+8NHxLDvmMmwVpAglMguSU5ON1kztQm71SXATdqilou4Xfqzf8U+J+mmbTgpYs8P5NE0YjPnaV8FnBkl8A/0zcTOmDkQTWoJG1nx6LKce2YMgl/uZcN3ngM5oSR84QSvmLnZrCaU7lNhos87x46S4WxGdeVJhib3Jo53C8awE4fKR9vn9+NCdvKV4LsXjhYvA3ZpK/zYV4sE9/SVUpgUSf77gLS5N/KzZpRR7g62tNH4HUm4H2JWp2gwgLi2YUGRMY0ADrQpNnFoaY2t7wwEVbw4lUCWtWAyE+zRbXUSQHRV8bLaqD5nLiUg3+AUfcjEd+OZyi9U7uFV439Cez+kDpL5oDlQ6e4G9I6BbIGeQeohoQneP4+2VsTnmKFxAvwbtllmggz08j+buJ1Rwhet0qjlnr4SLdeZMXVFFOZxjDQV1R/mHaDVQWM3mdNPoeXGqq3mmjnzrsmHO25aCv23ucb4M8b2QKuI1KGoAaPcQkZeFgDLf9j/TFA0YL6svVZMqFFl3iv7G4vOl8y0B62/RsHHKvy74oVFMZRrb3OgDxNESpbOJQncwCoFZjwGmMP2UKwNAc=
  app: sfmc-travis-tests

