sudo: required

language: ruby

services:
  - docker

env:
  global:
    - HEROKU_EMAIL="phillip.anderson@salesforce.com"
  matrix: 
    # This one is the API_KEY from the website (Account Settings -> API Key) ran through the travis encryption gem: 'travis encrypt HEROKU_PASSWORD=<Paste API Key>'
    - secure: btnyfXaPJX4FsOgLYpskSPjLRlEZBkAPsTRtscrBs+1SIcLKAAYfFb0ZDgWReK5qJu4dMPZkF8KeVV0UBqNoaL5k/67SsC52+xF6SSKjMHFM2d0i46BXvFsydEDtRLAkOPTzmRltN6COs9E7Rq6CeGApNuoTNlFU9kAwWqATZ3Zq6RjVuKLFGD270sSD7mwmBu5IKfH1jgLzsfNAaofHHtHI/s8/v4h7X07Bp3wsQBMyaN6YCYG7/VnxWIcBc/A1EcuRZFF8TXOaCgjhfWXwxYn47NpcAksZHcuIapXa30VUyAX/+U4cZM8mDEteJOd8Hj7P0p7G4Xg6kZYl9RtMMj7ugAg8wQxNPaXR9YXraJVaAkIJgg8l7ryhKDCeQ672A5HNWhRr9CsLjQauhj0dhOU5poiXKEzY7jSfgMZi75Oj8gdLEAYPVtMTlVQSOYTP1ouN9aBxqwWYysoghbnDsbHTWMfZt5RffO5YaI5X2dQeqDZwNnmHvMHK0L7oAes7fH40pHmCBA/q82p5jvY8IGpaCh2FXRGVmKdPLmjo63SSrOKgiuZOpf7pMkTewTE8Wdvf7EwDgidAtwb+bupNM6BLC7Gpqe32EdCPtTG8o9aMHx3niWUYzmHGyw4wYS1LiiDNki208S9MumMybrD6pHINdQ8BmO/eO37n22/xGP0=

before_script:
  # This will update the heroku CLI to include the required container:release functionality
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - chmod +x heroku-setup.sh

script:
  # Should the script be stopped if one part errors? If using -x, should the echo's be removed?
  #- set -ex
  
  # Setup Heroku. Basically Makes Heroku Think it was already logged into.
  - ./heroku-setup.sh

  - heroku container:login

  # Heroku builds and pushes the Image to the app's registry registry
  - heroku container:push web -a sfmc-travis-tests

  # Heroku needs to release the Image from its registry
  - heroku container:release web -a sfmc-travis-tests
  
notifications:
  email:
    recipients:
      - phillip.anderson@salesforce.com
      #- ahoem@salesforce.com
      #- API team or others?
    on_success: always
    on_failure: always
