sudo: required

language: ruby

services:
  - docker

env:
  global:
    - HEROKU_EMAIL=""
  matrix: 
    - secure: dl2UY8qkOYpmN26ED6TV/b+XcBCFfJtw1KMfJgBVOJOs02acH6wPwP9JHx/1bsJyFoLPUoBSkLa2geWlRJPpj00hobSyzM6jhHQ6tp3l/toDbWe3BGCj/Aad3+yde1JJ+J6jr99C0WbNUQ+90KPhJ59tNxR/alqOqrN1b/OE6/cwBxYRBQC+9Fu50ggUJpY8b5EpALxoZlUcLIQfGyCldY/VUMVur/0X3HK1Fz+eLnN/HFfsN0dHMWeUT3RQpOfKms03IlszF84EGn02zOYkb/Kxx9cGXdBvx2QFp1UQvocJIBs2XFzg9EkCjCgKqXAcoEOD6O2/ngEXeyO4ZsMNieNvpyZbWJe0AFuh+XZCV8fJkQ26zt80k8HWVl68qH+G+F6rs0a1BpkqipgFnVq5ZAayUH0p+AYne5kfsXHnta8CreImcWRoDNpw54anTb+dJyVJ+WeKwQ1NJW7Yzy0YkdP+RtcmbzNWM/A2+w9Na/59L1JcNr7UBPgVgqNO19/sKqKzHJYhe63SZimBlKYgqt5DbCfq+8DNZOMQh/ZrKMV6tTeiGDyi4rNewnqJB8FqsEUC5qRLvuP3zaSWONXDbDDbFgz3VQhgwR93EjFDOWvFYEsRJdXRAh9GHDr2oWP2llVW86D20PMTlRzOOAPySHFysNAWsK/OSg6zdGqRF0s=
    # This Key is the encrypted value for the Authorization created specifically for Travis: (HEROKU_API_KEY=<KEY>)
    - secure: tKvOXeC84mG2tKQuBsNHNXYPNs9jibRu/eBStH6bbT8o0IccOUOJucS1aqFle62rutAYxcZMZ6kZ+nrn9JGtPcEQc/3uTko0GKWRx2RPw2yiDi6VP+T1MP9IkYFPo5IhW+QLvUl8lid6mTxzF/hHqnFxJU5UPGMnAZZ8oGDmBdx/0YwiYaoujd+LZSoNIBuLTA3uln0unj0bY8Od/VxYZo8dO6i1cAxcvXKCV5TSTFOm4dhfZhYMsHquOmA7VCZdhifxS0/tJpROIDBwmu+afFGfLQ/Rco/hl5Fu0hIQu8sUgz+KmGe3IXGcfm3tekdn1/XbcpmFIZy7iRS9El29PqLhbgqkc85pYdYEqnaABn+ZgEmcYeR+ixggvZ13tDMUhAOWlnaF6w+uajmsP8946fNSGMk2glPg2JSm9tcuWyhBtPPSwx5lOq+k3E/X0kxL+pJg9sVvwymYVax5xEMg+SHP6RG6pjAj9T8srRlSGUgNc4rZ/cK5ukPo81Rx/OywZb+VpaIGvin9Jj//bWRXYMX9CA4RXB4+RXpfH/ul3zQYOlKOA4ZPQaBDP9Lnj/MaLPbShy+f+9DGaLObqEaTcOFCXDRbF12CAqhEd2Jbljbx7RLnolrdp5bBFSTsGWSUEN4zt6NorIJefPjvKXX6rN8OvL3OvM/goJzMETTVilw=

before_script:
  - docker rmi -f philasfwork/sfmc-swagger-ui
  - docker rmi -f registry.heroku.com/sfmc-travis-tests/web
  - chmod +x docker-commands.sh

script:
  - heroku run "./docker-commands.sh" -a sfmc-travis-tests
  #- docker build ./main -t philasfwork/sfmc-swagger-ui
  #- docker images
  #- curl -n -X PATCH https://api.heroku.com/apps/sfmc-travis-tests/formation -d "{ 'updates':[{'type':'web','docker_image':'philasfwork/sfmc-swagger-ui'}]}" -H "Content-Type: application/json" -H "Accept: application/vnd.heroku+json; version=3.docker-releases"
  #- heroku login
  #- heroku container:login
  #- heroku container:push web -a sfmc-travis-tests
  #- heroku container:release web

#deploy:
#  provider: heroku
#  api_key:
#    secure: Lp0vleoGnuyOouFWDNbcwqXT2AXYstaTmOrpRsppU8fFUKskCPup7xph6PPdnCL0DC2UMvUZfLXDrISUfbSOAu4dC4FoX9klR9B/8Bw2mikZb5lcNcjZwFKS3EdEdbYKIseol4bLq6Y0dDqf+ICKojNwwG7pQNmRBFhR8iKlrVKVEWHqwsZDOsYt+4JWjS4ASHwlaL6kFa3NpHxxH8AZ4xTBTFHzocNsbRYw+R7ZcVnsrDRBjUKryDPkwP4VVsIKuosP4sCWTfpRUxtLLvi1ahm5puSKGwGuPgCD44uYfe7X5zr/KdsblEZRhjvG2F4Vag543X0tb7jIDiHqn9DmlpDKGBf81MNPcnSY/jqFI6QwYOS5mN+nQK7ZyGsggUMmXfprfPff8klAAKfyCWBlf3c31O65TnWPfguw/zV0omNJmhWOndFt+9RVwoCILYBRWQqKQNp9urFZXk6JtiNtxtS43jk+QzW2eF3Q0Y6OdUtxJtbWy4GC9sQxEufTuWf/tOXE+fOw3tfDa3ngkt9zyuhJ0QQ/u4DuQ5oE2dB7yhWKwWR57pbOdXL58Jy1lak+IHJCXmspb1U5CahsQIW9QurO4z4l24x/LlhrSCs5Jr/W5o+J5tIJ8aY+REBWynsVKhU4t1lLVP6ndtWGESB2cNHr/imug7HzrvxkR6+LgIs=
#  app: sfmc-travis-tests