sudo: required

language: ruby

services:
  - docker

env:
  secure: pUVyGwAig9QO+1AqGV9ZQsUSWt2JtZxR5QEqe70NGa57i35ysODEynl7l3ew8blUkOldG6yXljXtyzEgL8BpVC6CcNSc4oAsQ1WV3lqaCta9/l+ruo8z2TM5p4cKqZTqMq0QAuJjRBbRAsqnk3R96NEWF3F6eJ84WG+pQFTcRM3z1QfXYYShFkF+fySZ24cuLZHNTLBk6UZK7D59aQt+wjhwFkLLZuvq0LnjkpHQ1EYsSv5ebMA2GjG2J0sI+znRqhgDJD0dsXtvtso920eGawMZFm/SbtMOuZj6Rmoq8ajtzB7dVIZW/safxZhkGe5pKbdQyqjyVzPBJx0uztPvta0t662MHoeWmNIsaeXZRS1lgndH1wgLcANyIyBo9uvP0QAB1MjXOIWIdR15e8y2g45siaZxE9Fo4geAaZhjbFTpiejsrfGXLMlTt/XcEGAsnJauNnFe2fOeJihfIMnnqrHKASek8LqdgUA3wTnC+LnIKIyekJHhxT2XJSNLCk9Eixa/GxhyaH75OixQgPcO5mttR2H9/Kf3vfugRO6rcSk6xXLjLvYA/wvMhQ7M9znB8xcHz9musYsBW8JtwddPcojLgo05oEAjXrB3sFBAvsrRltk/yqXbSzNQrRBpFo3x3g2hFtiKawzJSDzv+Hy5HUTi3LE9fSgWURFMWPfpIMU=

before_script:
  - docker rmi -f philasfwork/sfmc-swagger-ui
  - docker rmi -f registry.heroku.com/sfmc-travis-tests/web

script:
  - heroku run "HEROKU_EMAIL=`phillip.anderson@salesforce.com` HEROKU_API_KEY=`$HEROKU_API_KEY` ./docker-commands.sh" -a sfmc-travis-tests
  #- docker build ./main -t philasfwork/sfmc-swagger-ui
  #- docker images
  #- curl -n -X PATCH https://api.heroku.com/apps/sfmc-travis-tests/formation -d "{ 'updates':[{'type':'web','docker_image':'philasfwork/sfmc-swagger-ui'}]}" -H "Content-Type: application/json" -H "Accept: application/vnd.heroku+json; version=3.docker-releases"
  #- heroku login
  #- heroku container:login
  #- heroku container:push web -a sfmc-travis-tests
  #- heroku container:release web

#deploy:
#  provider: heroku
#  api_key:
#    secure: Lp0vleoGnuyOouFWDNbcwqXT2AXYstaTmOrpRsppU8fFUKskCPup7xph6PPdnCL0DC2UMvUZfLXDrISUfbSOAu4dC4FoX9klR9B/8Bw2mikZb5lcNcjZwFKS3EdEdbYKIseol4bLq6Y0dDqf+ICKojNwwG7pQNmRBFhR8iKlrVKVEWHqwsZDOsYt+4JWjS4ASHwlaL6kFa3NpHxxH8AZ4xTBTFHzocNsbRYw+R7ZcVnsrDRBjUKryDPkwP4VVsIKuosP4sCWTfpRUxtLLvi1ahm5puSKGwGuPgCD44uYfe7X5zr/KdsblEZRhjvG2F4Vag543X0tb7jIDiHqn9DmlpDKGBf81MNPcnSY/jqFI6QwYOS5mN+nQK7ZyGsggUMmXfprfPff8klAAKfyCWBlf3c31O65TnWPfguw/zV0omNJmhWOndFt+9RVwoCILYBRWQqKQNp9urFZXk6JtiNtxtS43jk+QzW2eF3Q0Y6OdUtxJtbWy4GC9sQxEufTuWf/tOXE+fOw3tfDa3ngkt9zyuhJ0QQ/u4DuQ5oE2dB7yhWKwWR57pbOdXL58Jy1lak+IHJCXmspb1U5CahsQIW9QurO4z4l24x/LlhrSCs5Jr/W5o+J5tIJ8aY+REBWynsVKhU4t1lLVP6ndtWGESB2cNHr/imug7HzrvxkR6+LgIs=
#  app: sfmc-travis-tests