sudo: required

language: ruby

services:
  - docker

env:
  global:
    - HEROKU_EMAIL="phillip.anderson@salesforce.com"
  matrix: 
    # This one is the API_KEY from the website called HEROKU_PASSWORD
    - secure: ZF/Led/P76qZ8GbgDbA7RchBV5YWeH7Xhsnmv3hkhCgzHOVpHOzeeCMOgN8vqVO7vJa8OLohYXXQ2KR/mHwDW5/MM4DMpa0GBx0Cd48x3RITNpZf9CTisXHVR4EJHpnCcs7tb6gyGEHW6RVOYyBhTqTqLK+xWz+W+XrZYGHre+OkFBJvBMdsq4ziJ115f/+CCBFhlILcmnjYOPS/5cH/A/CiUGu1L+A0zJ980wC2OVpbWpX2/CcDVUKv2nW0E4ZA2GwHRC7TCPAc7jy17KONOEyWIth5RzqGjRvKrfF4ixNgJqyjOJqetxmrSchHEUQvv/pwQ1Yd2cz1/s8QrgGXXIx4NKFDcqXEQkPmjRHl8d+4DhLqqHkX/ofKFF+H5hNeyQrmAfXW91o1mMRiN2cEf8BN3EFqs1fo9myvh/ijIs9XccAi+X9ePOo53GaWxVdKpNsNLYcWdh27QSBdlew52NQDUQhYJXspp1YEZf4AERmw2UySAWnN3fXoXtdCyMthOdaL4RMVvGUxWZsAvx17iupCvhxR/furQ9LPfeNm5A7QeII7UE7g9i3VnkwgouLuZgLfn7TYnOEt5evcdt/g2ES27oh25FfZ41LAAEK33tbemfXuOAFQLpq2y8a7zpaEsMCNaa84b76E0x9zPWPfhTyB/Xc633F0ykTFcMDX7xY=
    # This one is the auth:token called HEROKU_PASSWORD:
    #- secure: AfhOCkwI4n3byd/iY2Tf+IWhUwicnDqIGEyyPPuGDAgYqZbf4iRpoVpO3YxI701F8cIr293NnFDuLLn3o2MknIl42BUdsAXJh49FvYym894ho45hoODfFQyacr61x8eBgbcwTM4l6c6uh1FUNULvNx/ocIpHoPejjlS/dgX03ZMJcmXVNANOKE3fjCTDq7+g1RsIHnJs3PIcljYOrqekMNrSrcX4GF8pdhl/FUfaCdajxPVbQPWkd4YpkP1/7ASXIIIdynS8Yq9RDk9odlceMH5lrMleDi8L3UvYbSwwfd1wJQFY8EiOXvpk1ZNYyIBHZabPh3c5gP+bhFg2GTpHmeZHfLZUKqSOEDt8MLFnJOgJ7eW26JL8/dHcf/7g2GxCrMDjiCitQQeP4tMK6ihYALENcul7zA7GeO4nTY6nOI49bZcs+e48tpP0B9YuMBbW5eU9B6UFBmM+ouiqqak65YhJ2BoTkOu4O7ZFlcjoF0hZM3BX+SnuVHmaF12JYbr29pN83G+WUX9zQJSIrO+xc1x7Nm1Qx4VOIyOjD0ch3Z35lojSlShbSBu7XYfYA5vrd9XA9kcnO3310Rc6PnsCna+SuyV9dMQEkpJfr96gkZEKkcnpWTEqw7evwKxCg300ywlIVsRS2EV5O2bAN7IBWQ0IQAH8ZIOOmtdVHRbEmG0=
    # This one is the auth:token called HEROKU_API_KEY
    #- secure: MLbI1e20ZbPwisuLqemqNU5veNVdF2J5WeCNCgho3rNE8B7BvBsnRz9wFx8U25+HVpRaUKgo+g5lSdn8F4tvXWvYBMywsyrRRnOj35mOqoA0h9raq6PhBYTZ+u3/qWxsqhFlAUwgZd5sEvrRNHuw+YymUTPjbUoPeMNoTACJx2GdoJdeTF7mKH9HUapPu/P06hJU4iUK9ezGS1BEZ++fHbH+2IeMiYVWqQMIS/m5E977ZVnPJMXg+D69UoNCp/44Ar1P0GVwvxIr/TaZpl6a5a4jEjmz8POrn+0DNgXQrxthfryIkOjptzPNul1Z1319X8n1yQBo46tQi4sxChCgNs/Q0RSVmSGMvLVHnRAkPwUg+caOjy2+KGZpiGfLQEzcJ1yP1e5uHFmGIfuJBcnAr1ZdV54jm8M3IIdXNq40nSQBciNF93SRl6lKo4valbkjEH9WnpIt/yMfU+4ZfAOIdZoq4ynLG2bx79q+U/EU14wzjaskuYqchIK0Rm41AYUQy8YI+7ccHwhDDM1swygewBWtJR4crqL9lV8BOUivIes7peO1gRXEUJsiudQfXeVLdUfASNQ/zfseo/CVRYMCvI0aW5WxktF69ULFUY9tWGvapUxr19/rx2EWUrg4nJzONa+WuOFdOMEz5ghT0ItLgG4HmNb8W2G2ECZ3HSy6bdE=
    # This Key is the encrypted value for the Authorization created specifically for Travis: (HEROKU_API_KEY=<KEY>)
    #- secure: tKvOXeC84mG2tKQuBsNHNXYPNs9jibRu/eBStH6bbT8o0IccOUOJucS1aqFle62rutAYxcZMZ6kZ+nrn9JGtPcEQc/3uTko0GKWRx2RPw2yiDi6VP+T1MP9IkYFPo5IhW+QLvUl8lid6mTxzF/hHqnFxJU5UPGMnAZZ8oGDmBdx/0YwiYaoujd+LZSoNIBuLTA3uln0unj0bY8Od/VxYZo8dO6i1cAxcvXKCV5TSTFOm4dhfZhYMsHquOmA7VCZdhifxS0/tJpROIDBwmu+afFGfLQ/Rco/hl5Fu0hIQu8sUgz+KmGe3IXGcfm3tekdn1/XbcpmFIZy7iRS9El29PqLhbgqkc85pYdYEqnaABn+ZgEmcYeR+ixggvZ13tDMUhAOWlnaF6w+uajmsP8946fNSGMk2glPg2JSm9tcuWyhBtPPSwx5lOq+k3E/X0kxL+pJg9sVvwymYVax5xEMg+SHP6RG6pjAj9T8srRlSGUgNc4rZ/cK5ukPo81Rx/OywZb+VpaIGvin9Jj//bWRXYMX9CA4RXB4+RXpfH/ul3zQYOlKOA4ZPQaBDP9Lnj/MaLPbShy+f+9DGaLObqEaTcOFCXDRbF12CAqhEd2Jbljbx7RLnolrdp5bBFSTsGWSUEN4zt6NorIJefPjvKXX6rN8OvL3OvM/goJzMETTVilw=

before_script:
  - docker rmi -f philasfwork/sfmc-swagger-ui
  - docker rmi -f registry.heroku.com/sfmc-travis-tests/web
  - chmod +x docker-commands.sh
  - chmod +x heroku-setup.sh

script:
  #- heroku auth:whoami
  - ./heroku-setup.sh
  - ./docker-commands.sh
  #- heroku run "HEROKU_EMAIL='$HEROKU_EMAIL' HEROKU_PASSWORD='$HEROKU_PASSWORD' ./docker-commands.sh" -a sfmc-travis-tests -s free
  #- heroku run "HEROKU_EMAIL='$HEROKU_EMAIL' HEROKU_API_KEY='$HEROKU_API_KEY' ./docker-commands.sh" -a sfmc-travis-tests
  #- docker build ./main -t philasfwork/sfmc-swagger-ui
  #- docker images
  #- curl -n -X PATCH https://api.heroku.com/apps/sfmc-travis-tests/formation -d "{ 'updates':[{'type':'web','docker_image':'philasfwork/sfmc-swagger-ui'}]}" -H "Content-Type: application/json" -H "Accept: application/vnd.heroku+json; version=3.docker-releases"
  #- echo "phillip.anderson@salesforce.com"; echo "$HEROKU_PASSWORD"
  #- (echo "phillip.anderson@salesforce.com"; echo "$HEROKU_PASSWORD") | heroku login
  #- heroku login
  #- heroku container:login
  #- heroku container:push web -a sfmc-travis-tests

#deploy:
#  provider: heroku
#  api_key:
#    secure: Lp0vleoGnuyOouFWDNbcwqXT2AXYstaTmOrpRsppU8fFUKskCPup7xph6PPdnCL0DC2UMvUZfLXDrISUfbSOAu4dC4FoX9klR9B/8Bw2mikZb5lcNcjZwFKS3EdEdbYKIseol4bLq6Y0dDqf+ICKojNwwG7pQNmRBFhR8iKlrVKVEWHqwsZDOsYt+4JWjS4ASHwlaL6kFa3NpHxxH8AZ4xTBTFHzocNsbRYw+R7ZcVnsrDRBjUKryDPkwP4VVsIKuosP4sCWTfpRUxtLLvi1ahm5puSKGwGuPgCD44uYfe7X5zr/KdsblEZRhjvG2F4Vag543X0tb7jIDiHqn9DmlpDKGBf81MNPcnSY/jqFI6QwYOS5mN+nQK7ZyGsggUMmXfprfPff8klAAKfyCWBlf3c31O65TnWPfguw/zV0omNJmhWOndFt+9RVwoCILYBRWQqKQNp9urFZXk6JtiNtxtS43jk+QzW2eF3Q0Y6OdUtxJtbWy4GC9sQxEufTuWf/tOXE+fOw3tfDa3ngkt9zyuhJ0QQ/u4DuQ5oE2dB7yhWKwWR57pbOdXL58Jy1lak+IHJCXmspb1U5CahsQIW9QurO4z4l24x/LlhrSCs5Jr/W5o+J5tIJ8aY+REBWynsVKhU4t1lLVP6ndtWGESB2cNHr/imug7HzrvxkR6+LgIs=
#  app: sfmc-travis-tests