swagger: "2.0"
info:
  description: ""
  version: "1.0.0" #used for a services API version tracking
  title: "SFMC Transactional Swagger"
#host: "www.exacttargetapis.com" #not required - owned by docs

#####
# Section info is defined by tags and tag objects
#####
tags:
- name: "transactional sends"
- name: "transactional defintions"

schemes:
- "https"
paths:
  /transactional/v1/email/definition/{tsd_external_key}/send:
    parameters:
      - in: path
        name: tsd_external_key
        description: "your transactional send defintion"
        required: true  #always needed because it's a path paramater
        type: string
    post:
      operationId: the_corresponding_method_in_code2
      tags: #tags are used to group operations in Swagger UI.
      - "transactional sends"
      summary: "send a transactional EMAIL message"
      description: ""
      consumes: #this is the content-type header for the reponse
      - "application/json"
      produces: #this is the content-type header in the request
      - "application/json"
      parameters:
      - in: body
        name: "Send body"
        schema:
          allOf:
          - $ref: '#/definitions/emailRequest'
          - $ref: '#/definitions/globalSettings'
      responses:
        200:
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apiResponseBody'
            - $ref: '#/definitions/messageSendResponse'
  /transactional/v1/sms/definition/{tsd_external_key}/send:
    parameters:
      - in: path
        name: tsd_external_key
        description: "your transactional send defintion"
        required: true  #always needed because it's a path paramater
        type: string
    post:
      operationId: the_corresponding_method_in_code3
      tags: #tags are used to group operations in Swagger UI.
      - "transactional sends"
      summary: "send a transactional SMS message"
      description: ""
      consumes: #this is the content-type header for the reponse
      - "application/json"
      produces: #this is the content-type header in the request
      - "application/json"
      parameters:
      - in: body
        name: "Send body"
        schema:
          allOf:
          - $ref: '#/definitions/smsRequest'
          - $ref: '#/definitions/globalSettings'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/apiResponseBody'
            #type: object
  /transactional/v1/email/definition/{tsd_external_key}/status/messagekey/{message_key}:
    parameters:
      - in: path
        name: tsd_external_key
        description: "The triggered send defintion"
        required: true  #always needed because it's a path paramater
        type: string
      - in: path
        name: message_key
        description: "Unique message key to check status"
        required: true  #always needed because it's a path paramater
        type: string
    get:
      tags:
      - "transactional sends"
      summary: "fetches a paginated list of data"
      responses:
        200:
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apiResponseBody'
            - $ref: '#/definitions/messageWebhookResponse'

definitions:
#-- Global Definitions --------------------------------------------------
#----------------------------------------------------------------------
  #globalRequestMessage:  #ain't so such thing!  Actually, I couldn't figure out how to create a nest/shared inheritance model for EmailTo>MessageTo+GlobalTo>GlobalMessage w/o namespace conflicts
  globalRequestTo:
    type: object
    required:
      - MessageKey
      - SubscriberKey
    properties:
      MessageKey:
        type: string    
        description: Unique client-provided identifier for a specific message to a recipient that could be used to provide feedback for that specific message.
        example: '9691010a-1e59-48a0-b0d8-67d9a86dc470'
      SubscriberKey:
        type: "integer"
        format: "int64"
        description: TBD
        example: #
  globalRequestFrom:
    type: object
    properties:
      Name:
        type: string
        description: 'This is the name displayed when message is received (email only?)'
        example: 'NTO Notifications'    
  globalRequestAttributes:
    type: object
    properties:
      FirstName:
        type: string
        example: 'Robert'
      LastName:
        type: string
        example: 'Smith'
      State:
        type: string
        example: "Indiana or IN"
  globalSettings:
    type: object
    properties:
      Tags: 
        type: array
        description: "Meta data for reporting and tracking"
        items:
          type: string
          example: "tag1, tag2"
      ValidityPeriod:
        type: integer
        format: int32
        description: "Number of seconds, after this time if the message hasn't not been processed for whatever reason (system issue, blackout window) then no message will be sent."
      #DeliveryTime:
      #  type: string
      #  format: date-time
#-- Email Definitions ---
#-------------------------
  emailRequestFrom:
    type: object
    properties:
      Address: #email
        type: string
        description: 'For email channel, this would be the from address displayed when email is received. '
        example: 'notifications@nto.com'  
  emailRequestMessage:
    type: object
    properties:
      Subject:
        type: string
        description: "Subject field for email. OTT Message Name (optional)"
        example: "Your 2-factor passcode"
      CharacterSet:
        type: string
        description: TBD
        example: #
      HtmlBody:
        type: string
        description: 'For email only, can be used along with Text for Multipart MIME messages'
        example: 
  emailRequestTo:
    type: "object"
    properties:
      emailAddress:
        type: string
        description: TBD
        example: #
      Message:
        allOf:
         - $ref: '#/definitions/emailRequestMessage'
      Attributes:
        $ref: '#/definitions/globalRequestAttributes'
      CC:
        type: array
        items:
          type: string
          example: cc_example@example.com, cc2_example@example.com
          #$ref: '#/definitions/GenericEmailArrayObject'
      BCC:
        type: array
        items:
          type: string
          example: cc_example@example.com, cc2_example@example.com
  emailRequest:
    title: email message Request
    type: object
    properties:
      From:
        allOf: 
         - $ref: '#/definitions/globalRequestFrom'
         - $ref: '#/definitions/emailRequestFrom'
      Message:
        allOf:
      #  - $ref: '#/definitions/globalRequestMessage'
        - $ref: '#/definitions/emailRequestMessage'
      To:
        type: array
        items:
          allOf: 
            - $ref: '#/definitions/globalRequestTo'
            - $ref: '#/definitions/emailRequestTo'
      Options:
        $ref: '#/definitions/globalRequestOptions'

#-- SMS Definitions ---
#-------------------------
  smsRequestFrom:
    type: object
    properties:
      SenderID:  #sms
        type: string
        description: 'SMS identifier for who sent the message. OTT presence identifier (LINE Channel ID, Facebook Messenger Page ID, Apple Business Chat Business ID)'
        example: "MySenderID"
  smsRequestMessage:
    type: object
    properties:
      Text:
        type: string
        description: TBD
        example: "Your 2-factor passcode is 3484028"
      Encoding:
        type: string
        description: TBD
        example: #
      CharacterSet:
        type: string
        description: "Example UTF-8, ANSII"
        enum: ["UTF-8", "ASCII"]
      #ContentUrl:
      #  type: string
      #  description: 'MMS Location of the media to send'
      #  example: #
  smsRequestTo:
    type: "object"
    properties:    
      mobileNumber:
        type: "integer"
        format: "int32"
        description: TBD
        example: #
      replyToken:
        type: string
        description: TBD
        example: #
      Message:
      #  $ref: '#/definitions/globalRequestMessage'
        $ref: '#/definitions/smsRequestMessage'
      Attributes:
        $ref: '#/definitions/globalRequestAttributes'
  smsRequest:
    title: SMS message Request
    type: object
    properties:
      From:
        allOf: 
         - $ref: '#/definitions/globalRequestFrom'
         - $ref: '#/definitions/smsRequestFrom'
      Message:
        allOf:
      #  - $ref: '#/definitions/globalRequestMessage'
        - $ref: '#/definitions/smsRequestMessage'
      To:
        type: array
        items:
          allOf: 
            - $ref: '#/definitions/globalRequestTo'
            - $ref: '#/definitions/smsRequestTo'
      Options:
        $ref: '#/definitions/globalRequestOptions'

#------------------------------
  globalRequestOptions:
    type: object
    properties:
      Blackhold:
        type: boolean
        description: TBD
        example: false
      IngoreRecipientStatus:
        type: boolean
        description: TBD
        example: false
      TrackingEnabled:
        type: boolean
        description: TBD
        example: false
      #RequestType:
      #  type: string
      #  description: TBD
      #  example: "ASYNC"
      Subscribe:
        type: boolean
        description: TBD
        example: false
      Resubscribe:
        type: boolean
        description: TBD
        example: false
      Keyword:
        type: array
        description: TBD
        items:
          type: string
#---------------------------------
  apiResponseBody:
    type: object
    properties:
      requestId:
        type: string
        format: UUID v4
        example: "ba9633fa-5c8d-4c42-8efa-a16412ac0c53"
      requestErrorCode:
        type: integer
        example: 7005
      requestErrorMessage:
        type: string
        example: "Ensure you include all required fields in the body of the request"
  messageSendResponse:
    type: object
    properties:
      responses:
        type: array
        items: 
          type: object
          properties:
            MessageKey:
              type: string
              example: "9691010a-1e59-48a0-b0d8-67d9a86dc470"
            ErrorCode:
              type: integer
            ErrorMessage:
              type: string
  messageWebhookResponse:
    type: object
    properties:
      Event-type: 
        type: string
      Event-time:
        type: string
        format: date-time
      CompositeId:
        type: string
        example: "tsid.job.list.batch.sub"
      Sub:
        type: object
        properties:
          MessageKey:
            type: string
            format: UUID v4
            example: "9691010a-1e59-48a0-b0d8-67d9a86dc470"
          SubscriberKey: 
            type: string
      Event-data:
        type: object

