sudo: required

language: ruby
# rvm:
# 	- 2.4

services:
  - docker

before_script:
  - docker rmi -f philasfwork/sfmc-swagger-ui
  - docker rmi -f registry.heroku.com/sfmc-travis-tests/web

script:
  - docker build ./main -t philasfwork/sfmc-swagger-ui
  - docker images

deploy: 
  provider: heroku
  # run "travis encrypt $(heroku auth:token) --add deploy.api_key"
  # otherwise you will have to find and encrypt the Heroku key and put it in the tag below.
  #api_key: 
  app: sfmc-travis-tests